//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModMetaEntities : DbContext
    {
        public ModMetaEntities()
            : base("name=ModMetaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Code_ListTable1> tb_Code_ListTable1 { get; set; }
        public virtual DbSet<tb_Code_ListTable2> tb_Code_ListTable2 { get; set; }
        public virtual DbSet<tb_Code_ListTable3> tb_Code_ListTable3 { get; set; }
        public virtual DbSet<tb_Code_TreeTable2> tb_Code_TreeTable2 { get; set; }
        public virtual DbSet<tb_StandardBook> tb_StandardBook { get; set; }
        public virtual DbSet<tb_StandardCatalog> tb_StandardCatalog { get; set; }
        public virtual DbSet<tb_Code_SchoolStage> tb_Code_SchoolStage { get; set; }
        public virtual DbSet<tb_Code_ListTable1_Relationship> tb_Code_ListTable1_Relationship { get; set; }
        public virtual DbSet<tb_Code_Knowledge> tb_Code_Knowledge { get; set; }
        public virtual DbSet<tb_Code_BookReel> tb_Code_BookReel { get; set; }
        public virtual DbSet<tb_Code_ListTable3_Relationship> tb_Code_ListTable3_Relationship { get; set; }
        public virtual DbSet<ViewMod_Trunt_Branch> ViewMod_Trunt_Branch { get; set; }
    }
}
