//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MODResourceEntities : DbContext
    {
        public MODResourceEntities()
            : base("name=MODResourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Course> tb_Course { get; set; }
        public virtual DbSet<tb_CourseApp> tb_CourseApp { get; set; }
        public virtual DbSet<tb_Drip> tb_Drip { get; set; }
        public virtual DbSet<tb_Edition> tb_Edition { get; set; }
        public virtual DbSet<tb_Evidence> tb_Evidence { get; set; }
        public virtual DbSet<tb_InnerUser> tb_InnerUser { get; set; }
        public virtual DbSet<tb_LessonSet> tb_LessonSet { get; set; }
        public virtual DbSet<tb_Resource> tb_Resource { get; set; }
        public virtual DbSet<tb_ResourceModel> tb_ResourceModel { get; set; }
        public virtual DbSet<tb_Subject> tb_Subject { get; set; }
        public virtual DbSet<tb_TextBook> tb_TextBook { get; set; }
        public virtual DbSet<tb_VerifyResource> tb_VerifyResource { get; set; }
        public virtual DbSet<TBA_LessonSet> TBA_LessonSet { get; set; }
        public virtual DbSet<TBC_ResourceTypeEdition> TBC_ResourceTypeEdition { get; set; }
        public virtual DbSet<TBC_ResourceTypeGrade> TBC_ResourceTypeGrade { get; set; }
        public virtual DbSet<TBC_SubjectGrade> TBC_SubjectGrade { get; set; }
        public virtual DbSet<RsTempTable> RsTempTable { get; set; }
        public virtual DbSet<tb_Course_back> tb_Course_back { get; set; }
        public virtual DbSet<tb_ResourceApplicable> tb_ResourceApplicable { get; set; }
        public virtual DbSet<tb_ResourceKnowledge> tb_ResourceKnowledge { get; set; }
        public virtual DbSet<tb_ResourceTeachingModule> tb_ResourceTeachingModule { get; set; }
        public virtual DbSet<TBA_ResourceTeaching> TBA_ResourceTeaching { get; set; }
    
        public virtual int proc_CourseAnalys()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_CourseAnalys");
        }
    
        public virtual int proc_LessonSetAnalys()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_LessonSetAnalys");
        }
    
        public virtual ObjectResult<proc_pageView_Result> proc_pageView(string columns, string tbNames, string whereCondition, string orderColumns, Nullable<int> isOrderByASC, Nullable<int> currentPageIndex, Nullable<int> pageSize, ObjectParameter totalPages, ObjectParameter totalRecords)
        {
            var columnsParameter = columns != null ?
                new ObjectParameter("Columns", columns) :
                new ObjectParameter("Columns", typeof(string));
    
            var tbNamesParameter = tbNames != null ?
                new ObjectParameter("TbNames", tbNames) :
                new ObjectParameter("TbNames", typeof(string));
    
            var whereConditionParameter = whereCondition != null ?
                new ObjectParameter("WhereCondition", whereCondition) :
                new ObjectParameter("WhereCondition", typeof(string));
    
            var orderColumnsParameter = orderColumns != null ?
                new ObjectParameter("OrderColumns", orderColumns) :
                new ObjectParameter("OrderColumns", typeof(string));
    
            var isOrderByASCParameter = isOrderByASC.HasValue ?
                new ObjectParameter("IsOrderByASC", isOrderByASC) :
                new ObjectParameter("IsOrderByASC", typeof(int));
    
            var currentPageIndexParameter = currentPageIndex.HasValue ?
                new ObjectParameter("CurrentPageIndex", currentPageIndex) :
                new ObjectParameter("CurrentPageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_pageView_Result>("proc_pageView", columnsParameter, tbNamesParameter, whereConditionParameter, orderColumnsParameter, isOrderByASCParameter, currentPageIndexParameter, pageSizeParameter, totalPages, totalRecords);
        }
    
        public virtual int proc_ResourceAnalys()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ResourceAnalys");
        }
    
        public virtual int proc_ResourceCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ResourceCount");
        }
    
        public virtual ObjectResult<proc_Search_Result> proc_Search(string values, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var valuesParameter = values != null ?
                new ObjectParameter("Values", values) :
                new ObjectParameter("Values", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Search_Result>("proc_Search", valuesParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<proc_SearchUpdate_Result> proc_SearchUpdate(string values, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var valuesParameter = values != null ?
                new ObjectParameter("Values", values) :
                new ObjectParameter("Values", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_SearchUpdate_Result>("proc_SearchUpdate", valuesParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<proc_SearchVerify_Result> proc_SearchVerify(string values, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var valuesParameter = values != null ?
                new ObjectParameter("Values", values) :
                new ObjectParameter("Values", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_SearchVerify_Result>("proc_SearchVerify", valuesParameter, pageIndexParameter, pageSizeParameter);
        }
    }
}
