//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Course
    {
        public int ID { get; set; }
        public string CourseName { get; set; }
        public string Version { get; set; }
        public int EditionID { get; set; }
        public string ImgPath { get; set; }
        public string CoursePath { get; set; }
        public string Status { get; set; }
        public string CourseKey { get; set; }
        public string Coursetype { get; set; }
        public string Grade { get; set; }
        public string Subject { get; set; }
        public decimal FileSize { get; set; }
        public Nullable<int> TimeSpan { get; set; }
        public Nullable<int> BookReel { get; set; }
        public Nullable<int> SchoolStage { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}
