//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Code_ListTable1_Relationship
    {
        public System.Guid ID { get; set; }
        public int Start_ID { get; set; }
        public int End_ID { get; set; }
        public int Seq { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime ModifyDateTime { get; set; }
    }
}
