//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CourseApp
    {
        public int ID { get; set; }
        public int CourseID { get; set; }
        public string AppName { get; set; }
        public string Version { get; set; }
        public string Folder { get; set; }
        public int OrderType { get; set; }
        public int AppType { get; set; }
        public string AppKey { get; set; }
    }
}
