//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Code_SchoolStage
    {
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public string CodeName { get; set; }
        public Nullable<int> Limited { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public int Deleted { get; set; }
        public string Description { get; set; }
    }
}
