//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Evidence
    {
        public int ID { get; set; }
        public string ToKen { get; set; }
        public Nullable<int> IsWorking { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string Remark { get; set; }
        public string ErrorUrl { get; set; }
        public Nullable<int> Ke { get; set; }
        public Nullable<int> Yun { get; set; }
        public Nullable<int> Movie { get; set; }
        public Nullable<int> IsBuy { get; set; }
    }
}
