//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Files
    {
        public System.Guid ID { get; set; }
        public string FileName { get; set; }
        public string FileDescription { get; set; }
        public string FileExtension { get; set; }
        public int FileSize { get; set; }
        public string FilePath { get; set; }
        public int FileType { get; set; }
        public bool FinishStatus { get; set; }
        public int EncryptStatus { get; set; }
        public int ConvertStatus { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    }
}
