//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LessonSet
    {
        public System.Guid LessonSetID { get; set; }
        public Nullable<System.Guid> AttachID { get; set; }
        public string LessonSetName { get; set; }
        public string AttachName { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> Subject { get; set; }
        public Nullable<int> Edition { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string FileType { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> BookReel { get; set; }
    }
}
