//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Resource()
        {
            this.tb_ResourceKnowledge = new HashSet<tb_ResourceKnowledge>();
            this.tb_InnerUser = new HashSet<tb_InnerUser>();
            this.tb_InnerUser1 = new HashSet<tb_InnerUser>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<double> Number { get; set; }
        public string Title { get; set; }
        public Nullable<int> SchoolStage { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> Subject { get; set; }
        public Nullable<int> Edition { get; set; }
        public Nullable<int> BookReel { get; set; }
        public Nullable<int> Catalog { get; set; }
        public Nullable<int> ResourceType { get; set; }
        public Nullable<int> ResourceStyle { get; set; }
        public Nullable<int> ResourceLevel { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> TeachingStep { get; set; }
        public Nullable<int> TeachingStyle { get; set; }
        public System.Guid FileID { get; set; }
        public string Description { get; set; }
        public Nullable<int> IsVerify { get; set; }
        public Nullable<int> Purview { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UploadUser { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> DownCounts { get; set; }
        public Nullable<int> ScanCounts { get; set; }
        public string FileType { get; set; }
        public string BreviaryImgUrl { get; set; }
        public Nullable<decimal> ResourceSize { get; set; }
        public Nullable<int> IsRecommend { get; set; }
        public Nullable<System.Guid> MaterialID { get; set; }
        public string ComeFrom { get; set; }
        public Nullable<int> AppraisedCounts { get; set; }
        public Nullable<int> CollectCounts { get; set; }
        public string TeachingModules { get; set; }
        public string Applicable { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> Copyright { get; set; }
        public string CopyrightName { get; set; }
        public long Sort { get; set; }
        public Nullable<int> TimeSpan { get; set; }
        public Nullable<int> ResourceClass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ResourceKnowledge> tb_ResourceKnowledge { get; set; }
        public virtual tb_VerifyResource tb_VerifyResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InnerUser> tb_InnerUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InnerUser> tb_InnerUser1 { get; set; }
    }
}
