//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_LessonSet
    {
        public int ID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> SchoolStageID { get; set; }
        public Nullable<int> EditionID { get; set; }
        public Nullable<decimal> TotalCounts { get; set; }
        public Nullable<decimal> TotalTimeSpan { get; set; }
        public Nullable<decimal> TotalSize { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}
