//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_ResourceTeaching
    {
        public int ID { get; set; }
        public Nullable<int> SchoolStageID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> EditionID { get; set; }
        public Nullable<int> BookReelID { get; set; }
        public Nullable<decimal> TotalCounts { get; set; }
        public Nullable<decimal> TotalSize { get; set; }
        public Nullable<decimal> CountsLess1M { get; set; }
        public Nullable<decimal> Counts1To10M { get; set; }
        public Nullable<decimal> Counts10To100M { get; set; }
        public Nullable<decimal> CountsOver100M { get; set; }
        public Nullable<decimal> CountsKJ { get; set; }
        public Nullable<decimal> CountsHDKJ { get; set; }
        public Nullable<decimal> CountsTP { get; set; }
        public Nullable<decimal> CountsDH { get; set; }
        public Nullable<decimal> CountsYP { get; set; }
        public Nullable<decimal> CountsWB { get; set; }
        public Nullable<decimal> CountsSJ { get; set; }
        public Nullable<decimal> CountsSP { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.DateTime> AnalysDate { get; set; }
    }
}
