//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBC_ResourceTypeEdition
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public int StyleID { get; set; }
        public int EditionID { get; set; }
        public int SchoolStageID { get; set; }
        public int SubjectID { get; set; }
        public Nullable<int> TotalCounts { get; set; }
        public Nullable<System.DateTime> CountDate { get; set; }
    }
}
